### ISSUE TITLE
Village.ReputationHandler crashes server

### ISSUE THREAD

**Issue by Dead2** [FatherToast/SpecialAI#3]
Using Special AI 1.0.1 for 1.12.2
Forge 14.23.5.2801

Happened while mining coal ore with a tconstruct pickaxe.
Note: modpack contains Foamfix, Quark and several others that might affect things. Let me know if you want more information.

```
java.lang.NullPointerException: Ticking player
    at fathertoast.specialai.village.ReputationHandler.onBlockBreak(ReputationHandler.java:112)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1524_ReputationHandler_onBlockBreak_HarvestDropsEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.event.ForgeEventFactory.fireBlockHarvesting(ForgeEventFactory.java:321)
    at net.minecraft.block.Block.func_180653_a(Block.java:572)
    at net.minecraft.block.Block.func_176226_b(Block.java:564)
    at net.minecraft.block.Block.func_180657_a(Block.java:735)
    at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:327)
    at net.minecraft.server.management.PlayerInteractionManager.func_73075_a(PlayerInteractionManager.java:109)
    at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:316)
    at net.minecraft.world.World.func_72866_a(World.java:1993)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
    at net.minecraft.world.World.func_72870_g(World.java:1955)
    at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:642)
    at net.minecraft.world.World.func_72939_s(World.java:1734)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by FatherToast** [comment]
Fixed in version 1.0.1
